# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.CharField(max_length=500)),
                ('data_criacao', models.DateField(default=datetime.datetime(2017, 6, 1, 13, 40, 43, 144984))),
                ('data_publicacao', models.DateField()),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('data_criacao', models.DateField(verbose_name=datetime.datetime(2017, 6, 1, 13, 40, 43, 145985))),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='posts.Topico'),
        ),
    ]
