# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_criacao',
            field=models.DateField(default=datetime.datetime(2017, 6, 1, 16, 34, 39, 756587)),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data_criacao',
            field=models.DateField(default=datetime.datetime(2017, 6, 1, 16, 34, 39, 757587)),
        ),
        migrations.AlterField(
            model_name='topico',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
