# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170601_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_criacao',
            field=models.DateField(default=datetime.datetime(2017, 6, 1, 18, 25, 55, 265148)),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data_criacao',
            field=models.DateField(default=datetime.datetime(2017, 6, 1, 18, 25, 55, 266149)),
        ),
    ]
